name: CD
on:
    push:
        branches:
            - master

jobs:
    lint:
        name: "Deploy"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              with:
                fetch-depth: 0
            
            - uses: shimataro/ssh-key-action@v2
              with:
                key: ${{ secrets.SSH_KEY }}
                known_hosts: ${{ secrets.KNOWN_HOSTS }}

            - run: git push ${{ secrets.SERVER }} master 
              name: Deploy
